name: 'api-server'

on:
  workflow_call:
    inputs:
      event:
        required: true
        type: string

jobs:
  merge-main:
    if: ${{ inputs.event == 'merge-main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Checkout
        uses: actions/checkout@v2
      - name: yarn install
        run: yarn install
      - name: yarn build
        run: yarn build
      - name: release
        run: yarn semantic-release
  pr:
    if: ${{ inputs.event == 'pr' }}
    runs-on: ubuntu-latest
    steps:
      - name: api-server pr
        run: echo "api-server pr"