name: 'api-server'

on:
  workflow_call:
    inputs:
      event:
        required: true
        type: string
      npm-token:
        required: true
        type: string

jobs:
  merge-main:
    if: ${{ inputs.event == 'merge-main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Log sec
        run: echo "Test ${{ inputs.npm-token }}"
      - name: Checkout
        uses: actions/checkout@v3
      - name: yarn install
        run: yarn install
      - name: yarn build
        run: yarn build
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ inputs.npmToken }}
  pr:
    if: ${{ inputs.event == 'pr' }}
    runs-on: ubuntu-latest
    steps:
      - name: api-server pr
        run: echo "api-server pr"