name: main
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  merge-main:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}
    outputs:
      affected_apps: ${{ steps.get_affected_apps.outputs.affected_apps }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: lswc
        uses: ./.github/actions/last-successful-workflow-commit
        id: lswc
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow_filename: main.yml
      - run: echo "${{ steps.lswc.outputs.commit_hash }}""git add .
      - name: Get affected apps
        uses: ./.github/actions/affected
        id: get_affected_apps
      - name: Log sec
        run: |
            echo "PUSH_NPM ${{ secrets.PUSH_NPM }}"
      - name: Configure target SHA
        run: |
            SHA=$(git rev-parse --verify HEAD)
            echo "TARGET_SHA=$SHA" >> $GITHUB_ENV
            echo "TARGET_SHA=$SHA" > target-sha.txt
      - name: Upload the target sha reference
        uses: actions/upload-artifact@v2
        with:
          name: TargetSHA
          path: target-sha.txt
  pr:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    outputs:
      affected_apps: ${{ steps.get_affected_apps.outputs.affected_apps }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - name: Get affected apps
        uses: ./.github/actions/affected
        id: get_affected_apps
  editor-merge-main:
    uses: ./.github/workflows/editor.yml
    with:
      event: merge-main
    needs: merge-main
    if: contains(needs.merge-main.outputs.affected_apps, 'editor')
  editor-pr:
    uses: ./.github/workflows/editor.yml
    with:
      event: pr
    needs: pr
    if: contains(needs.pr.outputs.affected_apps, 'editor')
  api-server-merge-main:
    uses: ./.github/workflows/api-server.yml
    with:
      event: merge-main
    secrets:
      token: ${{ secrets.PUSH_NPM }}
    needs: merge-main
    if: contains(needs.merge-main.outputs.affected_apps, 'api-server')
  api-server-pr:
    uses: ./.github/workflows/api-server.yml
    with:
      event: pr
    needs: pr
    if: contains(needs.pr.outputs.affected_apps, 'api-server')
  prosite-merge-main:
    uses: ./.github/workflows/prosite.yml
    with:
      event: merge-main
    needs: merge-main
    if: contains(needs.merge-main.outputs.affected_apps, 'pro-site')
  prosite-pr:
    uses: ./.github/workflows/prosite.yml
    with:
      event: pr
    needs: pr
    if: contains(needs.pr.outputs.affected_apps, 'pro-site')