name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}
    steps:
      - uses: actions/checkout@v2
        name: Checkout [main]
        with:
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - run: npm install
      - run: npx nx affected:apps --plain
      - run: npx nx affected:libs --plain
  pr:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    outputs:
      affected_apps: ${{ steps.affected_apps.outputs.AFFECTED_APPS }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - run: npm install
      - name: Get affected apps
        run: |
          AFFECTED=$(npx nx affected:apps --plain)
          echo "::set-output name=AFFECTED_APPS::$AFFECTED"
        id: affected_apps
      - run: echo "${{ steps.affected_apps.outputs.AFFECTED_APPS }}"
  editor:
    uses: ./.github/workflows/editor.yml
    needs: pr
    if: contains(needs.pr.outputs.affected_apps, 'editor')
  prosite:
    uses: ./.github/workflows/prosite.yml
    needs: pr
    if: contains(needs.pr.outputs.affected_apps, 'prosite')