name: 'pro-site'

on:
  workflow_call:
    inputs:
      event:
        required: true
        type: string

jobs:
  merge-main:
    if: ${{ inputs.event == 'merge-main' }}
    runs-on: ubuntu-latest
    steps:
      - name: pro-site merge main
        run: echo "pro-site merge main"
  pr:
    if: ${{ inputs.event == 'pr' }}
    runs-on: ubuntu-latest
    steps:
      - name: pro-site pr
        run: echo "pro-site pr"