name: revert-k8s-image.yml
on:
  workflow_dispatch:
    
jobs:
  revert:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: main.yml
          workflow_conclusion: success
          name: TargetSHA
      - name: Configure target SHA
        run: |
          cat target-sha.txt >> $GITHUB_ENV
      - name: Check Target SHA in Github env
        run: |
          echo "Target SHA is ${{ env.TARGET_SHA }}"