name: revert-k8s-image.yml
on:
  workflow_dispatch:
    inputs:
      run_id:
        description: 'The run id of the deploy workflow(production-build-deploy.yml) you want to revert to'
        required: true
jobs:
  revert:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: main.yml
          run_id: ${{ github.event.inputs.run_id }}
          name: TargetSHA
      - name: Configure target SHA
        run: |
          cat target-sha.txt >> $GITHUB_ENV
      - name: Check Target SHA in Github env
        run: |
          echo "Target SHA is ${{ env.TARGET_SHA }}"